package ripelookup

// code generated by gen.go DO NOT EDIT
import "github.com/kentik/patricia"
import "github.com/kentik/patricia/string_tree"

var v6tree = string_tree.NewTreeV6()

func init() {
	// 2001::/23
	v6tree.Set(patricia.NewIPv6Address([]byte{32, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 23), "whois.iana.org")
	// 2001:200::/23
	v6tree.Set(patricia.NewIPv6Address([]byte{32, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 23), "whois.apnic.net")
	// 2001:400::/23
	v6tree.Set(patricia.NewIPv6Address([]byte{32, 1, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 23), "whois.arin.net")
	// 2001:600::/23
	v6tree.Set(patricia.NewIPv6Address([]byte{32, 1, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 23), "whois.ripe.net")
	// 2001:800::/23
	v6tree.Set(patricia.NewIPv6Address([]byte{32, 1, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 23), "whois.ripe.net")
	// 2001:a00::/23
	v6tree.Set(patricia.NewIPv6Address([]byte{32, 1, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 23), "whois.ripe.net")
	// 2001:c00::/23
	v6tree.Set(patricia.NewIPv6Address([]byte{32, 1, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 23), "whois.apnic.net")
	// 2001:e00::/23
	v6tree.Set(patricia.NewIPv6Address([]byte{32, 1, 14, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 23), "whois.apnic.net")
	// 2001:1200::/23
	v6tree.Set(patricia.NewIPv6Address([]byte{32, 1, 18, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 23), "whois.lacnic.net")
	// 2001:1400::/23
	v6tree.Set(patricia.NewIPv6Address([]byte{32, 1, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 23), "whois.ripe.net")
	// 2001:1600::/23
	v6tree.Set(patricia.NewIPv6Address([]byte{32, 1, 22, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 23), "whois.ripe.net")
	// 2001:1800::/23
	v6tree.Set(patricia.NewIPv6Address([]byte{32, 1, 24, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 23), "whois.arin.net")
	// 2001:1a00::/23
	v6tree.Set(patricia.NewIPv6Address([]byte{32, 1, 26, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 23), "whois.ripe.net")
	// 2001:1c00::/22
	v6tree.Set(patricia.NewIPv6Address([]byte{32, 1, 28, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 22), "whois.ripe.net")
	// 2001:2000::/20
	v6tree.Set(patricia.NewIPv6Address([]byte{32, 1, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 20), "whois.ripe.net")
	// 2001:3000::/21
	v6tree.Set(patricia.NewIPv6Address([]byte{32, 1, 48, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 21), "whois.ripe.net")
	// 2001:3800::/22
	v6tree.Set(patricia.NewIPv6Address([]byte{32, 1, 56, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 22), "whois.ripe.net")
	// 2001:4000::/23
	v6tree.Set(patricia.NewIPv6Address([]byte{32, 1, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 23), "whois.ripe.net")
	// 2001:4200::/23
	v6tree.Set(patricia.NewIPv6Address([]byte{32, 1, 66, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 23), "whois.afrinic.net")
	// 2001:4400::/23
	v6tree.Set(patricia.NewIPv6Address([]byte{32, 1, 68, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 23), "whois.apnic.net")
	// 2001:4600::/23
	v6tree.Set(patricia.NewIPv6Address([]byte{32, 1, 70, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 23), "whois.ripe.net")
	// 2001:4800::/23
	v6tree.Set(patricia.NewIPv6Address([]byte{32, 1, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 23), "whois.arin.net")
	// 2001:4a00::/23
	v6tree.Set(patricia.NewIPv6Address([]byte{32, 1, 74, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 23), "whois.ripe.net")
	// 2001:4c00::/23
	v6tree.Set(patricia.NewIPv6Address([]byte{32, 1, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 23), "whois.ripe.net")
	// 2001:5000::/20
	v6tree.Set(patricia.NewIPv6Address([]byte{32, 1, 80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 20), "whois.ripe.net")
	// 2001:8000::/19
	v6tree.Set(patricia.NewIPv6Address([]byte{32, 1, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 19), "whois.apnic.net")
	// 2001:a000::/20
	v6tree.Set(patricia.NewIPv6Address([]byte{32, 1, 160, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 20), "whois.apnic.net")
	// 2001:b000::/20
	v6tree.Set(patricia.NewIPv6Address([]byte{32, 1, 176, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 20), "whois.apnic.net")
	// 2003::/18
	v6tree.Set(patricia.NewIPv6Address([]byte{32, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 18), "whois.ripe.net")
	// 2400::/12
	v6tree.Set(patricia.NewIPv6Address([]byte{36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 12), "whois.apnic.net")
	// 2600::/12
	v6tree.Set(patricia.NewIPv6Address([]byte{38, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 12), "whois.arin.net")
	// 2610::/23
	v6tree.Set(patricia.NewIPv6Address([]byte{38, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 23), "whois.arin.net")
	// 2620::/23
	v6tree.Set(patricia.NewIPv6Address([]byte{38, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 23), "whois.arin.net")
	// 2800::/12
	v6tree.Set(patricia.NewIPv6Address([]byte{40, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 12), "whois.lacnic.net")
	// 2a00::/12
	v6tree.Set(patricia.NewIPv6Address([]byte{42, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 12), "whois.ripe.net")
	// 2c00::/12
	v6tree.Set(patricia.NewIPv6Address([]byte{44, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 12), "whois.afrinic.net")
}
